# Generated by Django 3.1.5 on 2021-01-11 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_brands'),
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Inventory Name')),
                ('quan_in_stock', models.IntegerField(verbose_name='Total In')),
                ('sales_quan', models.IntegerField(verbose_name='Total out')),
                ('real_Quantity', models.IntegerField()),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Stocks',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Inventory Name')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'Stocks',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.AddField(
            model_name='stocks',
            name='Stores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.stores', verbose_name='Stores'),
        ),
    ]
