# Generated by Django 3.1.4 on 2020-12-31 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendor'},
        ),
    ]
