# Generated by Django 3.1.5 on 2021-01-11 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0001_initial'),
        ('Products', '0006_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oder_date', models.DateField(verbose_name='date_created')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='amount')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.customer')),
                ('orderItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.orderitem')),
            ],
        ),
    ]
