# Generated by Django 3.1.5 on 2021-01-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='oder_date',
            field=models.DateField(auto_now=True, verbose_name='date_created'),
        ),
    ]
