# Generated by Django 3.1.5 on 2021-01-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20201231_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Brands name')),
            ],
            options={
                'verbose_name': 'Brands',
                'verbose_name_plural': 'Brands',
            },
        ),
    ]
